import React from 'react';
import ReactDOM from 'react-dom/client';
import './index.css';
import App from './App';
import reportWebVitals from './reportWebVitals';
// --- ADD THESE 3 LINES START ---
import { Amplify } from 'aws-amplify';
import { Authenticator } from '@aws-amplify/ui-react';
//import config from './amplifyconfiguration.json'; // This file was auto-generated by 'amplify push'
import awsExports from './aws-exports'

console.log("Loading AWS Config:", awsExports);
// --- ADD THESE 3 LINES END ---
Amplify.configure(awsExports);
const root = ReactDOM.createRoot(document.getElementById('root'));
root.render(
  <React.StrictMode>
    {/* This Provider MUST wrap App for useAuthenticator to work */}
    <Authenticator.Provider>
      <App />
    </Authenticator.Provider>
  </React.StrictMode>
);

// If you want to start measuring performance in your app, pass a function
// to log results (for example: reportWebVitals(console.log))
// or send to an analytics endpoint. Learn more: https://bit.ly/CRA-vitals
reportWebVitals();

